# Generated by Django 5.2.4 on 2025-08-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsletter_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('journalist', 'Journalist'), ('editor', 'Editor'), ('publisher', 'Publisher')], max_length=20),
        ),
    ]
