# Generated by Django 5.2.4 on 2025-08-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsletter_approved_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='author',
            new_name='journalist',
        ),
    ]
